name: Test and publish charm

# On push to a "special" branch, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests
# where a "special" branch is one of main/master or track/**, as
# by convention these branches are the source for a corresponding
# charmhub edge channel.

on:
  workflow_dispatch:
    secrets:
      CHARMHUB_TOKEN:
        required: true
  push:
    branches:
      - main
      - track/**
    secrets:
      CHARMHUB_TOKEN:
        required: true

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/test_and_publish_charm.yaml@v2.0.0
    secrets: inherit
